CREATE TABLE `tb_goods` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(24) DEFAULT NULL COMMENT '用户id',
  `goods_company` varchar(255) DEFAULT NULL COMMENT '商品公司',
  `goods_type` varchar(10) DEFAULT NULL COMMENT '产品类型',
  `goods_name` varchar(255) DEFAULT NULL COMMENT '产品名字',
  `goods_desc` varchar(255) DEFAULT NULL COMMENT '产品详情',
  `goods_price` decimal(10,2) DEFAULT NULL COMMENT '产品单价',
  `goods_unit` varchar(255) DEFAULT NULL COMMENT '产品单位',
  `goods_status` int(4) DEFAULT '0' COMMENT '产品状态0为未上架,1为已上架,2为已下架',
  `goods_stock` int(4) DEFAULT NULL COMMENT '库存数量',
  `pic` varchar(255) DEFAULT NULL COMMENT '图片地址',
  `audit_status` int(4) DEFAULT '0' COMMENT '审核状态0为默认状态,1为审核通过,2为审核失败',
  `remarks` varchar(255) DEFAULT NULL COMMENT '备注',
  `trade_clause` varchar(255) DEFAULT NULL COMMENT '贸易条款',
  `payment_by` varchar(255) DEFAULT NULL COMMENT '信用方式',
  `pricing_manner` varchar(255) DEFAULT NULL COMMENT '计价基准',
  `contractual_value_date` varchar(255) DEFAULT NULL COMMENT '计价日期',
  `port_of_dispatch` varchar(255) DEFAULT NULL COMMENT '发货港/提货点',
  `loading_date` varchar(255) DEFAULT NULL COMMENT '装载日',
  `pay_day` varchar(255) DEFAULT NULL COMMENT '支付日',
  `other_description` varchar(255) DEFAULT NULL COMMENT '其他说明',
  `place_of_origin` varchar(255) DEFAULT NULL COMMENT '油产地',
  `oil_type` varchar(255) DEFAULT NULL COMMENT '油种类',
  `api` varchar(255) DEFAULT NULL COMMENT 'api度',
  `sulphur_content` varchar(255) DEFAULT NULL COMMENT '含硫量%',
  `acid_value` varchar(255) DEFAULT NULL COMMENT '酸值mgkoh/g',
  `carbon_residue` varchar(255) DEFAULT NULL COMMENT '残炭%',
  `nickel` varchar(255) DEFAULT NULL COMMENT '镍ppm',
  `vanadium` varchar(255) DEFAULT NULL COMMENT '钒ppm',
  `shrink` varchar(255) DEFAULT NULL COMMENT '>350摄氏度质量收缩率（%）',
  `file_point` varchar(255) DEFAULT NULL COMMENT '原油指标文件',
  `premiums_discounts` varchar(255) DEFAULT NULL COMMENT '升贴水',
  `creat_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8;