#服务器端口
server:
  port: 8200
  servlet:
    context-path: /finepetro-admin

#数据源配置
spring:
  datasource:
    url: ${finepetro.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}
  freemarker:
    suffix: .html
    request-context-attribute: request

jpush:
  appKey: 9325ea96802112de6540276a
  masterSecret: b5be61a29d2a31ce340907b6
