#服务器端口
server:
  port: 8112
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 3
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
  mvc:
    servlet:
      load-on-startup: 1


#数据源配置
spring:
  datasource:
    url: ${finepetro.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}
  cloud:
    sentinel:
      eager: true

jpush:
  appKey: 9325ea96802112de6540276a
  masterSecret: b5be61a29d2a31ce340907b6

mybatis-plus:
    #增加枚举类
  typeEnumsPackage: org.springblade.common.enums
  typeAliasesPackage: org.springblade.common.entity

  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.EnumTypeHandler
ribbon:
  eager-load:
    enabled: true
    clients: blade-foreward-user


